# This is a basic workflow to help you get started with Actions

name: PR_Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  issue_comment:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "tests"
  tests:
    # The type of runner that the job will run on
    if: contains(github.event.comment.body, 'run tests')
    runs-on: macOS-latest
    env:
          XC_VERSION: ${{ '11.5' }}
          XC_PROJECT: ${{ 'PRActions.xcodeproj' }}
          XC_SCHEME: ${{ 'PRActions' }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Select latest Xcode
          run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
        - uses: actions/checkout@v2
        - name: Run Unit and UI Tests
          run: /usr/bin/xcodebuild test -project "$XC_PROJECT" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'
