# This is a basic workflow to help you get started with Actions

name: PR_Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [created, edited, opened, synchronize, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "tests"
  tests:
    # The type of runner that the job will run on
    if: contains(github.event.comment.body, 'run tests')
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: 
          xcodebuild clean test -project PRActions.xcodeproj -scheme PRActions -destination "platform=iOS Simulator,name=iPhone 8" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

